### ISSUE TITLE
Improving the report

### ISSUE THREAD

**Issue by thelfenbaum** [laviealon/RoutineOptimizer-SpringBoot#10]
- add accessibility reflection on our project
- make sure that when we reference code in design document, we reference specific components (potentially find ways to link to specific lines?)
- explain lack of pull requests indicating major changes or design decisions
- explain why there are no specific pull requests or commit messages associated with the adapter pattern or dependency injection pattern
- 'better diagrams' -- need more advice from Tabeeb on what that means

**Comment by thelfenbaum** [comment]
split up issue into multiple more specific ones

**Comment by thelfenbaum** [comment]
documentation:
- no single character variables
- class doc
- method doc

**Comment by thelfenbaum** [comment]
Design decisions to add to document:
- current choice of pages for GUI
- decided to leave non-fixed tasks as non-fixed to leave opportunity for future expansions of the program to utilize that flexibility (even though they currently function just like fixed tasks once they are scheduled and put into weekly schedule

**Comment by laviealon** [comment]
I will be reassigning this issue to phase 2.2.
