### ISSUE TITLE
Which design patterns would be fitting for our code? 

### ISSUE THREAD

**Issue by laviealon** [laviealon/RoutineOptimizer-SpringBoot#13]
Research a few design patterns and see if they have a place in our code. Go about this using the following template:

- Step 1 - choose a new design pattern.
- Step 2 - decide if it is fitting for our code.
- Step 3 - if yes, move to step 4. If no, go back to step 1.
- Step 4 - draw a UML diagram specific to our code (+ any new classes/interfaces) of how we will integrate the pattern into our code
- Step 5 - respond to this issue with the design pattern name, the problem it solves, and the UML diagram for review

--------

Steps for later specific issues once certain design patterns are agreed on:

- Step 1 - create a branch for implementing the design pattern and implement all skeleton code (with method and class headers plus docstrings)
- Step 2 - complete code by filling in method bodies
- Step 3 - pull request and review by the team, resolving any merge conflicts
- Step 4 - merge

**Comment by issamarabi** [comment]
Tabeeb said that the adapter design pattern was good enough, didn't he?

**Comment by laviealon** [comment]
Design patterns for each team member to research:

- @laviealon: builder, factory (both), dependency injection
- @thelfenbaum: composite, strategy, template
- @JMH-0402: memento, command, decorator
- @RunyuXia: facade, proxy, iterator
- @Asensio55: observer

**Comment by laviealon** [comment]
The builder design patterns and both factory design patterns don't apply here.

We can fix the hard dependency in `Week` entities (on a list of `Day` entities) using dependency injection. The `Week` constructor will take a `Day[]` argument, with the precondition that the list contains exactly seven Day entities and that their dates are consecutive. When constructing a `Week` (in UI/Main), an `Injector` class will construct this list based on user input and feed it into the `Week` constructor, guaranteeing the precondition set by the `Week` constructor.

Attached is a UML diagram.
![Screen Shot 2021-11-28 at 2 10 01 PM](https://user-images.githubusercontent.com/79278018/143782416-f7fa82bb-640f-496e-96f6-8043c18163e6.png)

**Comment by JMH-0402** [comment]
The design patterns Decorator and command don't apply to our program.

The memento design pattern could possibly be worked into our code when we ask the user to schedule a task into their schedule, we could create a memento of the schedule before the schedule gets changed, then if the user decides that the schedule is not how they would want it after the program schedules the task, then the user would let the program know and the program would make the schedule the same state as the memento 

[Note Nov 28, 2021.pdf](https://github.com/laviealon/RoutineOptimizer-SpringBoot/files/7614816/Note.Nov.28.2021.pdf)

**Comment by RunyuXia** [comment]
Facade Pattern 
--- could be used to fix week's dependency on the day class, works similar to the dependency injection. 
--- could be helpful if we want to group related classes together by creating a higher-level interface. Might be useful in cleaning up the UI.

Proxy and iterator don't apply to our program.

**Comment by thelfenbaum** [comment]
composite: could be really cool way to redesign projects, but would take a lot of work for not much refactoring (most of what it would allow is new functionality) so we would need to discuss

strategy: not directly applicable. meant for situation where many many classes are implementing different versions of same code. could potentially be way to redesign putter or scheduler around different task types, but I don't think it's necessary

template: seems to be a super helpful framework for complex algorithms. I could see a way to apply it to scheduler or putter, but that would mean redesigning both and I'm not sure the refactoring is worth the effort

**Comment by laviealon** [comment]
Doesn't look like observer is relevant to our code. @Asensio55 can let us know in tomorrow's meeting if he thinks differently.
