### ISSUE TITLE
Fixing project interface

### ISSUE THREAD

**Issue by thelfenbaum** [laviealon/RoutineOptimizer-SpringBoot#14]
1. decide how to split up project class
2. decide which level of clean architecture each of these components are
3. fix dependencies
4. implement composite pattern to create project entities so that subtasks can have different lengths? (see design pattern sheets)

**Comment by laviealon** [comment]
**Idea for re-designing `Task` and `Project` objects**

Have `<<Schedulable>>` and `<<Puttable>>` interfaces, where `Project` and `NonFixedTask` extend `<<Schedulable>>` and `FixedTask` extend `<<Puttable>>`. The Putter class only takes Puttables and the Schedulable class only takes Schedulables (I think this follows interface segregation and Liskov sub). When a Schedulable is fed into the Scheduler, the Scheduler returns a list of Puttables which is immediately fed into the Putter class.
![Screen Shot 2021-11-28 at 3 06 51 PM](https://user-images.githubusercontent.com/79278018/143784119-c16e9ac4-9efc-46b9-b465-649fc5f268a9.png)

**Comment by thelfenbaum** [comment]
what I have been able to conclude so far:

- project should definitely not be an interface. should remove static tag and make helper methods private
- after through investigation, I feel that project is a use case: it applies  business rules, it calls on entities, and nothing else

goal in meeting with Alon:
- what does refactoring it look like? should we maybe just leave as is?
- comparable level of mess to scheduler and putter, should we be adopting wider approach to all 3?

**Comment by laviealon** [comment]
I am in complete agreement that Project is a use case, and the class name should thus be reverted to the original: CreateProject (or PlanProject; something along those lines. Calling it Project suggests it is an entity). 

Other than that, I'm not sure about your reasoning for deciding that Scheduler, Putter, and Project need to be refactored. If you could elaborate that would be great.

**Comment by laviealon** [comment]
> **Idea for re-designing `Task` and `Project` objects**
> 
> Have `<<Schedulable>>` and `<<Puttable>>` interfaces, where `Project` and `NonFixedTask` extend `<<Schedulable>>` and `FixedTask` extend `<<Puttable>>`. The Putter class only takes Puttables and the Schedulable class only takes Schedulables (I think this follows interface segregation and Liskov sub). When a Schedulable is fed into the Scheduler, the Scheduler returns a list of Puttables which is immediately fed into the Putter class. ![Screen Shot 2021-11-28 at 3 06 51 PM](https://user-images.githubusercontent.com/79278018/143784119-c16e9ac4-9efc-46b9-b465-649fc5f268a9.png)

Idea: maintain memory of a `<<Puttable>>`'s status as a NonFixedFixed with an attribute "WasSchedulable" set to true, per @thelfenbaum's comment about the usefulness of maintaining a `<<Puttable>>`'s status as one.

**Comment by thelfenbaum** [comment]
This idea is becoming for attractive. especially because of DIP. do you want me to try and implement this in a branch?

**Comment by laviealon** [comment]
We decided to simply make Project a use case named MakeProject.
