### ISSUE TITLE
Testing with Mockito

### ISSUE THREAD

**Issue by JMH-0402** [laviealon/RoutineOptimizer-SpringBoot#15]
1. Research and look into whether or not using Mockito to test will be beneficial or not.
2. If useful, look into how to implement Mockito style testing into our code and what needs to be done in order to use Mockito(what we need to download).

**Comment by JMH-0402** [comment]
Mockito will be a beneficial way of testing to our program.  It allows us to test each program without having any dependencies in our tests to any other class except for our testing class, which allows our tests to fully test the class without having to worry about bugs in other classes. We can implement this using the following guide, https://www.toptal.com/java/a-guide-to-everyday-mockito.

**Comment by laviealon** [comment]
Great! Next time you can close an issue when you're done everything outlined in its spec.
