### ISSUE TITLE
Split up UserInterace 

### ISSUE THREAD

**Issue by laviealon** [laviealon/RoutineOptimizer-SpringBoot#2]
Split up the UserInterace class into different classes keeping with the Single Responsibility Principle.

- Step 1 - find the different responsibilities in UserInterace, and document them in a CRC (in the design document). 

- Step 2 -  in each class in the CRC, document all the methods and their responsibilities.
- Step 3 - create a branch for splitting up the UI; build skeleton code (with method signatures and docstrings for methods) for each class which works with the other classes. 
- Step 4 - fill in method bodies.
- Step 5 - write tests for the different methods.
- Step 6 - review as a team and make appropriate edits.
- Step 7 - create a pull request associated with this branch, and link it to this issue to close it.
- Step 8 - if there are any issues with the pull, go back to step 6.

**Comment by thelfenbaum** [comment]
we did a lot of moving around. probably up to step 4. want people to sign off on it before we scratch our heads trying to resolve all the conflicts

**Comment by laviealon** [comment]
Done until step 4. Will make a new issue with the rest of the steps for phase 2.2.

**Comment by thelfenbaum** [comment]
we did not quite need to follow the steps initially proscribed in this issue. We moved around methods rather than rewriting them and occasionally split them up.
