### ISSUE TITLE
SerializableToWeekAdapter schedules Tasks as parent Tasks and does not maintain their "WasSchedulable" status

### ISSUE THREAD

**Issue by laviealon** [laviealon/RoutineOptimizer-SpringBoot#24]
In SerializableToWeekAdapter (lines 23-24), the adapter creates a week and puts parent tasks inside of it since the database maintains no memory of whether the tasks were NonFixedTasks or FixedTasks when saved. 

Possible solutions:
- Have a boolean column in the tasks table in the DB which is true if the task used to be non fixed and false otherwise
- Implement my design suggestion in issue #14 and give FixedTasks an attribute called "wasSchedulable" (alternatively "isFlexible", since so far flexibility in a schedule is the only reason we would keep track of whether a task used to be fixed or not). Task parent class implements the `<<Schedulable>>` interface, and FixedTask child class implements the `<<Puttable>>` interface.  Eliminate NonFixedTask entirely. Projects are just formed as a list of Task objects and we have a createProject use case which takes a bunch of data from the userInterface fed to it by a controller and creates a list of Task objects.

**Comment by thelfenbaum** [comment]
don't non-fixed tasks have different attributes than fixed ones? can't we just look for tasks with a due date (which are only non-fixed)?

**Comment by laviealon** [comment]
There is no due date attribute. Due date is a question asked in the UI and is fed into a scheduling method as a parameter. Once a non fixed task is scheduled there is no "memory" of it being a non fixed task other than the fact that that is its type, which is lost when saved to the database as a TaskSerializable.

**Comment by laviealon** [comment]
We decided that although it would be nice to maintain a memory of whether a task was fixed or non fixed, our code's functionality does not  "care" about whether a task was fixed or non fixed. That being said, it would be a nice feature for our program in the future since if a user wants the program to algorithmically change up their schedule it could know which tasks to move around and which ones not to.
