### ISSUE TITLE
Split up Controller and Checker

### ISSUE THREAD

**Issue by laviealon** [laviealon/RoutineOptimizer-SpringBoot#25]
Controller right now is an old class which works but violates SRP (from what it looks like). Figure out how to split them up.

**Comment by thelfenbaum** [comment]
I think @JMH-0402  and I can look at that tonight when we work on splitting the UI

**Comment by thelfenbaum** [comment]
controller is split in the UI_split branch.
checker does not violate SRP and therefore I do not see a reason to split it. If we adopt the controller split offered in the UI_split branch, then the methods in checker will only be called on by CheckerController. This is ideal, but we will see how this fits with the UI related needs.
