### ISSUE TITLE
Create methods for JS to build a week following successful sign-up

### ISSUE THREAD

**Issue by laviealon** [laviealon/RoutineOptimizer-SpringBoot#38]
- Got to branch frontend-2, and create a branch from there called frontend-2-timetableJS
- Create a file in front-end/timetable/js called buildWeek.js.
- Make a POST request to 'http://localhost:8080/build-week' with the user's id and startDate
- Make a GET request to 'http://localhost:8080/weeks/{userid}' 
- Make a JS function converting this week to timetable HTML

**Comment by RunyuXia** [comment]
finished step 1234, needs help on step 5 building HTML
