### ISSUE TITLE
How to link SpringBoot to a GUI?

### ISSUE THREAD

**Issue by laviealon** [laviealon/RoutineOptimizer-SpringBoot#4]
## Research how to link SpringBoot to a web-based GUI. ##

Communicate with collaborator working on #3 to ensure that the GUI being created is SpringBoot-compatible.

Some resources:

#### Person working on this: @laviealon ####

**Comment by laviealon** [comment]
**If we decide to use Angular**

- Build an Angular app and connect it to Spring Boot: [https://www.youtube.com/watch?v=W3ZZqmJfUqo](https://www.youtube.com/watch?v=W3ZZqmJfUqo)
- Add front-end to the Angular app (@Asensio55):  [https://www.baeldung.com/spring-boot-angular-web](https://www.baeldung.com/spring-boot-angular-web)

**Comment by laviealon** [comment]
**If we decide to use HTML/CSS/JS**

- Evan's video walks through adding a front end starting at ~ minute 45
- Further guide: [https://spring.io/guides/gs/serving-web-content/](url)

**Comment by RunyuXia** [comment]
https://www.youtube.com/watch?v=z_yRCVhNams&list=PLS1QulWo1RIafCnQcMlGdb8Nn4eZlksCQ&index=1
tutorial on
-connecting springboot to web application
-postman
