### ISSUE TITLE
Application not starting due to server port problem

### ISSUE THREAD

**Issue by issamarabi** [laviealon/RoutineOptimizer-SpringBoot#45]
Application not starting because Intellij runs an application on whichever port we set our application to run on at runtime. Find out how to fix.

**Comment by laviealon** [comment]
Fixed by killing Intellij's Java application that was running on the port using terminal. For Mac users: run `lsof -i :<port_number> | grep LISTEN` on terminal to check the PID of the application running on port <port_number>; kill the application using `kill -9 <PID>`.
