### ISSUE TITLE
Implementing exceptions

### ISSUE THREAD

**Issue by laviealon** [laviealon/RoutineOptimizer-SpringBoot#6]
Whenever our code throws an error prompted to user input (either immediately or later in the program run), we should build a customized exception to catch the error when it gets thrown. The work flow for this is as follows:

- When thinking of or coming across a throw exception, give a short description for why it was thrown
- Name the customized exception which will we will catch
- Assign yourself (or someone else who has agreed) to work on it
- Create a branch and implement the exception class
- Implement the try-catch statement in the UI which catches the exception (follow Hailey and Issam's template from Phase 1, foud in the UI)
- Test the statement
- Pull request the branch

Follow all these steps and track your work flow in the Google Doc linked below:
[https://docs.google.com/document/d/1YkFY30aTil0nbGlIYJpygUY44Vcq7E6ww268Ide6aPY/edit?usp=sharing](url)

**Comment by issamarabi** [comment]
No new exceptions for phase 2. We are using web alerts instead.
